name: Docs deployment

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
          pnpm run docs:build
          cd docs/.vitepress/dist
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git status
          git commit -m 'deploy'
          git push -f https://jinjiang:${{secrets.ACCESS_TOKEN}}@github.com/zhlint-project/zhlint.git master:gh-pages
          cd -
